import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import BootstrapClient from '@/components/BootstrapClient.js';

export const metadata = {
  title: "My Contenful Nextjs page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container">          
          {children}
          <BootstrapClient />
        </main>     
      </body>
    </html>
  );
}
